[dingtalk]
client_id = "$DINGTALK_CLIENT_ID"
client_secret = "$DINGTALK_CLIENT_SECRET"


[agent]
provider_type = "anthropic"
model = "deepseek-v4-flash"
api_key = "$BAIZHI_API_KEY"
base_url = "https://ai-api-gateway.app.baizhi.cloud/api/anthropic/v1"
max_steps = 1024

[agent.reflection]
max_passes = 1
