import { NAV_ROOT, type UiActionSpec } from "@effect-agent/effect-ui"

export const deckActions: readonly UiActionSpec[] = [
  { name: "deck.new", opens: "new" },
  { name: "deck.catalog", opens: "catalog" },
  { name: "deck.open", opens: "session" },
  { name: "deck.load", method: "GET", url: "/deck/api/session/{sessionId}/history", result: "/opened",
    params: { sessionId: { state: `${NAV_ROOT}/sessionId` } }, clear: ["/message/text", "/result/turn", "/result/retry"] },
  { name: "deck.reloadSession", method: "GET", url: "/deck/api/session/{sessionId}/history", result: "/opened",
    params: { sessionId: { state: `${NAV_ROOT}/sessionId` } } },
  { name: "deck.create", method: "POST", url: "/deck/api/session", result: "/result/open",
    clear: ["/create/sessionId", "/create/prompt"], refresh: ["deck"] },
  { name: "deck.openCreated", opens: "session", params: { sessionId: { state: "/result/open/session/sessionId" } } },
  { name: "deck.close", method: "POST", url: "/deck/api/session/{sessionId}/close", result: "/result/session", refresh: ["deck", "deck.load"] },
  { name: "deck.closeAll", method: "POST", url: "/deck/api/sessions/close-all", result: "/result/session", refresh: ["deck", "deck.load"] },
  { name: "deck.send", method: "POST", url: "/deck/api/session/{sessionId}/send", result: "/result/turn",
    clear: ["/message/text"], refresh: ["deck", "deck.load"] },
  { name: "deck.retry", method: "POST", url: "/deck/api/session/{sessionId}/retry", result: "/result/retry", refresh: ["deck", "deck.load"] },
  { name: "deck.allow", method: "POST", url: "/deck/api/consent/{callId}", result: "/result/consent", refresh: ["deck", "deck.load"] },
  { name: "deck.deny", method: "POST", url: "/deck/api/consent/{callId}", result: "/result/consent", refresh: ["deck", "deck.load"] },
  { name: "deck.removeLauncher", method: "DELETE", url: "/deck/api/launchers/{label}?kind={kind}", result: "/result/launcher", refresh: ["launchers"] },
  { name: "deck.reload", method: "GET", url: "/deck/api/deck", refresh: ["deck"] },
  { name: "deck.reloadLaunchers", method: "GET", url: "/deck/api/launchers", refresh: ["launchers"] },
  { name: "deck.reloadPresets", method: "GET", url: "/deck/api/presets", refresh: ["presets"] },
]
