/**
 * The markdown rendering of the portability inventory.
 *
 * Presentation only: it turns facts into the report body, and every count it
 * prints is derived from the rows it is handed.
 *
 * Every literal here is English: the file this writes is repository
 * documentation, so it follows the same English-first rule as the docs it
 * cites. A translation of the output alone would be undone by the next run.
 */

import type { AppInventory } from "./inventory-app.ts"

const floorLabel = (app: AppInventory): string => {
  if (app.declaredRuntimes !== undefined && app.declaredRuntimes.length > 0) {
    return "declared: " + app.declaredRuntimes.map((r) => `\`${r}\``).join(" · ")
  }
  return app.floor === "os" ? "`os` (has ambient dependencies)" : "undeclared · not yet measured"
}

export const renderInventory = (rows: readonly AppInventory[]): string => {
  const deps = rows.filter((a) => a.ambientIo.length > 0 || a.builtins.length > 0).length
  const portable = rows.length - deps
  const lines: string[] = []
  lines.push("# App portability inventory")
  lines.push("")
  lines.push("> **This file is generated by `bun scripts/inventory-apps.ts`; do not edit it by hand.**")
  lines.push("> Basis: `docs/architecture-rework.md` §7 (runtime portability) and §10's P1.")
  lines.push(">")
  lines.push("> This inventory **deliberately ignores** the exemption list in `effect.boundary.json`: an exemption")
  lines.push("> is the authorisation to \"write it this way\", not evidence that it \"can leave the OS host\". The")
  lines.push("> boundary check governs policy; what is reported here is fact.")
  lines.push("")
  lines.push("## Overview")
  lines.push("")
  lines.push(
    `${rows.length} apps in total: **${deps}** have ambient dependencies (today they can only run on os), **${portable}** are untouched by system APIs in code.`,
  )
  lines.push("")
  lines.push("| app | package | runtime floor | abi | ambient IO | node/bun builtins |")
  lines.push("|---|---|---|---|---|---|")
  for (const app of rows) {
    const cells = [
      `\`${app.dir.replace("apps/", "")}\``,
      `\`${app.name}\``,
      floorLabel(app),
      app.abi === undefined ? "— (no artifact)" : `\`${app.abi}\``,
      app.ambientIo.length === 0 ? "—" : String(app.ambientIo.length),
      app.builtins.length === 0 ? "—" : String(app.builtins.length),
    ]
    lines.push(`| ${cells.join(" | ")} |`)
  }
  lines.push("")
  lines.push("## Details")
  for (const app of rows) {
    if (app.ambientIo.length === 0 && app.builtins.length === 0) continue
    lines.push("")
    lines.push(`### ${app.dir} — \`${app.name}\``)
    lines.push("")
    lines.push("| file | fact |")
    lines.push("|---|---|")
    for (const hit of app.ambientIo) lines.push(`| \`${hit.file}\` | ambient: ${hit.detail} |`)
    for (const hit of app.builtins) lines.push(`| \`${hit.file}\` | builtin: \`${hit.detail}\` |`)
  }
  lines.push("")
  lines.push("## How to read this table")
  lines.push("")
  lines.push("- **Has ambient dependencies** → the app is bound to `os` today (§7.2's debt list). To make it portable,")
  lines.push("  first converge fs / network / process into injected capability objects, then have each of the three")
  lines.push("  runtime tiers implement them (§7.5-3).")
  lines.push("- **Undeclared · not yet measured** → the code does not touch system APIs, but **that is not enough**")
  lines.push("  to prove it can run in browser/sandbox: a package it depends on may touch them itself, or use")
  lines.push("  semantics that exist only on OS. Only an actual run counts (P3's acceptance).")
  lines.push("- **abi column** → only present for those with `effect.bundle.json`; a missing `runtimes` means")
  lines.push("  `[\"os\"]` (conservative default).")
  lines.push("- In-memory state that cannot be rebuilt after a kernel switch needs manual cross-checking and is")
  lines.push("  not in this table — see `docs/architecture-rework.md` §6.3.")
  lines.push("")
  return lines.join("\n")
}
