import * as React from "react"
import { createRoot, type Root } from "react-dom/client"
import { JSONUIProvider, Renderer, type ComponentRegistry } from "@json-render/react"
import { supportsConfigSpec, type ConfigMount, type ConfigSpec, type ConfigElementSpec } from "./config-spec.ts"
import { appendArrayRow, parseFieldValue, rewriteArrayRowPaths } from "./config-array.ts"

const withNodeIds = (spec: ConfigSpec): ConfigSpec => ({ ...spec, elements: Object.fromEntries(Object.entries(spec.elements).map(([id, element]) => [id, { ...element, children: element.children ? [...element.children] : undefined, props: { ...(element.props ?? {}), nodeId: id } }])) })
const assign = (target: Record<string, unknown>, path: string, value: unknown): void => { const parts = path.split("."); let current: Record<string, unknown> | unknown[] = target; parts.forEach((part, index) => { if (index === parts.length - 1) (current as Record<string, unknown>)[part] = value; else { const next = parts[index + 1], child = (current as Record<string, unknown>)[part]; if (child === undefined) (current as Record<string, unknown>)[part] = /^\d+$/.test(next) ? [] : {}; current = (current as Record<string, unknown>)[part] as Record<string, unknown> | unknown[] } }) }
const hasPath = (target: Record<string, unknown>, path: string): boolean => path.split(".").reduce<unknown>((current, part) => current && typeof current === "object" ? (current as Record<string, unknown>)[part] : undefined, target) !== undefined
const removeTree = (elements: Record<string, ConfigElementSpec>, id: string): void => { (elements[id]?.children ?? []).forEach(child => removeTree(elements, child)); delete elements[id] }
const rowsOf = (spec: ConfigSpec, id: string): string[] => (spec.elements[id]?.children ?? []).filter(child => spec.elements[child]?.props?.arrayRow === true)
const syncRows = (spec: ConfigSpec, id: string): void => { const array = spec.elements[id]; rowsOf(spec, id).forEach((row, index) => rewriteArrayRowPaths(spec.elements, row, `${String(array?.props?.fieldPath ?? id)}.${index}`)); let index = 0; (array?.children ?? []).forEach(child => { const props = spec.elements[child]?.props; if (props?.arrayAction === "remove") props.arrayIndex = index++ }) }
const addArrayControls = (spec: ConfigSpec): void => Object.entries(spec.elements).forEach(([id, element]) => { if (element.props?.role !== "array") return; const rows = rowsOf(spec, id), controls = rows.map((_, index) => { const control = `${id}-remove-${index}`; spec.elements[control] = { type: "Button", props: { label: "Remove", arrayAction: "remove", arrayNode: id, arrayIndex: index } }; return control }); const add = `${id}-add`; spec.elements[add] = { type: "Button", props: { label: "Add item", arrayAction: "add", arrayNode: id } }; element.children = [...rows, ...controls, add] })
export const makeConfigMount = (registry: ComponentRegistry) => (container: HTMLElement, input: unknown): ConfigMount => {
  const render = (root: Root, spec: ConfigSpec) => root.render(<JSONUIProvider registry={registry}><Renderer spec={spec as never} registry={registry} /></JSONUIProvider>)
  if (!supportsConfigSpec(input)) throw new Error("Config Spec does not support this structure")
  const spec = withNodeIds(input as ConfigSpec); addArrayControls(spec); const root = createRoot(container); container.replaceChildren(); render(root, spec)
  const onClick = (event: Event) => { const button = (event.target as HTMLElement).closest<HTMLButtonElement>("[data-array-action]"); if (!button) return; const id = button.dataset.arrayNode, array = id && spec.elements[id]; if (!id || !array) return; const rows = rowsOf(spec, id); if (button.dataset.arrayAction === "remove") { const row = rows[Number(button.dataset.arrayIndex)]; if (!row) return; removeTree(spec.elements, row); array.children = (array.children ?? []).filter(child => child !== row); syncRows(spec, id) } else if (button.dataset.arrayAction === "add" && array.props?.itemSchema) { const row = appendArrayRow(spec.elements, id, rows.length, array.props.itemSchema as never); const add = (array.children ?? []).find(child => spec.elements[child]?.props?.arrayAction === "add"); array.children = (array.children ?? []).filter(child => child !== add); const remove = `${id}-remove-${rows.length}`; spec.elements[remove] = { type: "Button", props: { label: "Remove", arrayAction: "remove", arrayNode: id, arrayIndex: rows.length } }; array.children.push(row, remove); if (add) array.children.push(add) } else return; render(root, spec) }
  container.addEventListener("click", onClick)
  return { read: () => { const value: Record<string, unknown> = {}; container.querySelectorAll<HTMLElement>('[data-ui="input"][data-path]').forEach(node => { const input = node.querySelector<HTMLInputElement | HTMLSelectElement>("input,select"); const path = node.dataset.path; if (input && path) { const out = parseFieldValue(node, input); if (out !== undefined) assign(value, path, out) } }); Object.entries(spec.elements).filter(([, element]) => element.props?.role === "array").forEach(([, element]) => { const path = String(element.props?.fieldPath ?? ""), rows = (element.children ?? []).filter(id => spec.elements[id]?.props?.arrayRow === true); if (rows.length && path) { rows.forEach((row, index) => { const rowPath = String(spec.elements[row]?.props?.fieldPath ?? `${path}.${index}`); if (!hasPath(value, rowPath)) assign(value, rowPath, {}) }) } else if (path && (element.children ?? []).every(id => spec.elements[id]?.props?.arrayAction !== undefined)) assign(value, path, []) }); return value }, dispose: () => { container.removeEventListener("click", onClick); root.unmount() } }
}
