import * as React from "react"
import * as SelectPrimitive from "@radix-ui/react-select"
import * as SwitchPrimitive from "@radix-ui/react-switch"

type Props = Record<string, unknown>
const value = (props: Props, key: string): string => String(props[key] ?? "")
const inputType = (props: Props): string => (props.inputType === "boolean" || props.inputType === "checkbox") ? "checkbox" : props.inputType === "number" || props.inputType === "integer" ? "number" : "text"
const optionValue = (option: unknown): string => JSON.stringify(option)

export const Stack = ({ props, children }: { props: Props; children?: React.ReactNode }) => <div className="ui-role-stack" data-ui="stack" data-dir={String(props.direction ?? "vertical")} data-role={String(props.role ?? "stack")} style={{ "--ui-gap": `${Number(props.gap ?? 8)}px` } as React.CSSProperties}>{children}</div>
export const Text = ({ props }: { props: Props }) => <div className="ui-role-text" data-ui="text">{value(props, "value")}</div>
export const Button = ({ props }: { props: Props }) => <button type="button" className="ui-role-button" data-ui="button" data-strategy={value(props, "strategy") || undefined} data-array-action={value(props, "arrayAction") || undefined} data-array-node={value(props, "arrayNode") || undefined} data-array-index={props.arrayIndex === undefined ? undefined : String(props.arrayIndex)}>{value(props, "label") || "Confirm"}</button>
export const Input = ({ props }: { props: Props }) => <label className="ui-role-input" data-ui="input" data-node={value(props, "nodeId")} data-path={value(props, "fieldPath")} data-kind={value(props, "fieldKind")}>{props.label !== undefined && <span>{value(props, "label")}</span>}{props.inputType === "select" ? <select defaultValue={props.unset === true ? "" : optionValue(props.rawValue ?? props.value)}><option value="">{props.required ? "Select an option" : "Unset"}</option>{Array.isArray(props.options) && props.options.map((option: unknown) => <option key={optionValue(option)} value={optionValue(option)}>{String(option)}</option>)}</select> : <input type={inputType(props)} defaultChecked={props.checked === true} defaultValue={value(props, "value")} placeholder={value(props, "placeholder")} readOnly={props.readOnly === true} />}</label>
export const Switch = ({ props }: { props: Props }) => <label className="ui-role-switch" data-ui="switch"><SwitchPrimitive.Root className="ui-role-switch-control" defaultChecked={Boolean(props.checked)}><SwitchPrimitive.Thumb className="ui-role-switch-thumb" /></SwitchPrimitive.Root>{props.label !== undefined && <span>{value(props, "label")}</span>}</label>
export const Select = ({ props }: { props: Props }) => <label className="ui-role-select" data-ui="select">{props.label !== undefined && <span>{value(props, "label")}</span>}<SelectPrimitive.Root defaultValue={value(props, "value")}><SelectPrimitive.Trigger className="ui-role-select-trigger"><SelectPrimitive.Value placeholder={value(props, "placeholder") || "Select"} /></SelectPrimitive.Trigger><SelectPrimitive.Portal><SelectPrimitive.Content><SelectPrimitive.Viewport>{Array.isArray(props.options) && props.options.map((option: Props) => <SelectPrimitive.Item key={value(option, "value")} value={value(option, "value")}><SelectPrimitive.ItemText>{value(option, "label") || value(option, "value")}</SelectPrimitive.ItemText></SelectPrimitive.Item>)}</SelectPrimitive.Viewport></SelectPrimitive.Content></SelectPrimitive.Portal></SelectPrimitive.Root></label>
