import { NAV_ROOT, type UiActionSpec } from "@effect-agent/effect-ui"

export const boardActions: readonly UiActionSpec[] = [
  { name: "board.new", opens: "new" },
  { name: "board.open", opens: "task" },
  { name: "board.openDocuments", opens: "documents" },
  { name: "board.openDocument", opens: "outline" },
  { name: "board.openEvents", opens: "events" },
  { name: "board.create", method: "POST", url: "/board/api/tasks", result: "/createResult",
    clear: ["/create/title", "/create/body"], refresh: ["table"] },
  { name: "board.load", method: "GET", url: "/board/api/tasks/{taskId}", result: "/selected",
    params: { taskId: { state: `${NAV_ROOT}/taskId` } } },
  { name: "board.save", method: "PATCH", url: "/board/api/tasks/{taskId}", result: "/selectedResult",
    refresh: ["table"] },
  { name: "board.delete", method: "DELETE", url: "/board/api/tasks/{taskId}", result: "/selectedResult",
    refresh: ["table"] },
  { name: "board.retry", refresh: ["table"] },
  { name: "board.createDocument", method: "POST", url: "/board/api/documents", result: "/docResult",
    params: { title: { state: "/docDraft/title" } }, clear: ["/docDraft/title"], refresh: ["documents"] },
  { name: "board.deleteDocument", method: "DELETE", url: "/board/api/documents/{docId}", result: "/docResult",
    refresh: ["documents"] },
  { name: "board.loadDocument", method: "GET", url: "/board/api/documents/{docId}", result: "/outline/read",
    params: { docId: { state: `${NAV_ROOT}/docId` } } },
  { name: "board.retitle", method: "POST", url: "/board/api/documents/{docId}", result: "/outlineResult",
    params: { docId: { state: "/outline/read/docId" }, version: { state: "/outline/read/version" },
      op: { state: "/outline/rename" } },
    clear: ["/outline/rename/title"], refresh: ["board.loadDocument"] },
  { name: "board.insertNode", method: "POST", url: "/board/api/documents/{docId}", result: "/outlineResult",
    params: { docId: { state: "/outline/read/docId" }, version: { state: "/outline/read/version" },
      op: { state: "/outline/insert" } },
    clear: ["/outline/insert/text"], refresh: ["board.loadDocument"] },
]
